CREATE TABLE notes (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	text TEXT,
	due DATETIME,
	done INT NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY(note_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
