CREATE TABLE todos (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id VARCHAR(36) NOT NULL UNIQUE,
	user_name VARCHAR(36) NOT NULL,
	text TEXT,
	due DATETIME,
	done TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(user_name) REFERENCES users(name),
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
