CREATE TABLE users (
	id VARCHAR(36) NOT NULL,
	name VARCHAR(36) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
