requires 'Kossy', '0.19';
requires 'DBI', '1.628';
requires 'DBD::mysql', '4.024';
requires 'DateTime', '1.03';
requires 'FindBin', '1.51';
requires 'Teng', '0.20';
requires 'DateTime::Format::MySQL', '0.04';
requires 'Task::Plack', '0.28';
requires 'Data::GUID::URLSafe', '0.005';
requires 'Digest::SHA', '5.84_01';
requires 'Config::Simple', '4.58';






